class Image
	const Texture atlas = {"atlas-v45.png", size:{1024,1024}}
	global const Image VideoScreen = {"lib/core/play/media/VideoScreen0.png", atlas, {444,444}, [{x1:2,y1:2,x2:442,y2:332,w:440,h:330},{x1:2,y1:336,x2:442,y2:776,w:440,h:440}]}
	global const Image LargeButton = {"lib/core/play/media/LargeButton.png", atlas, {427,65}, [{x1:446,y1:2,x2:869,y2:63,w:423,h:61}]}
	global const Image LargeButtonAccent = {"lib/core/play/media/LargeButtonAccent1.png", atlas, {427,65}, [{x1:446,y1:132,x2:868,y2:193,w:422,h:61},{x1:446,y1:67,x2:869,y2:128,w:423,h:61}]}
	global const Image Button = {"lib/core/play/media/Button.png", atlas, {305,65}, [{x1:446,y1:197,x2:747,y2:258,w:301,h:61}]}
	global const Image ButtonAccent = {"lib/core/play/media/ButtonAccent1.png", atlas, {305,65}, [{x1:446,y1:327,x2:746,y2:388,w:300,h:61},{x1:446,y1:262,x2:747,y2:323,w:301,h:61}]}
	global const Image SmallButton = {"lib/core/play/media/SmallButton.png", atlas, {172,45}, [{x1:446,y1:392,x2:614,y2:433,w:168,h:41}]}
	global const Image SmallButtonAccent = {"lib/core/play/media/SmallButtonAccent1.png", atlas, {172,45}, [{x1:446,y1:437,x2:613,y2:478,w:167,h:41},{x1:618,y1:392,x2:786,y2:433,w:168,h:41}]}
	global const Image Rat = {"media/Rat.png", atlas, {104,104}, [{x1:446,y1:482,x2:546,y2:582,w:100,h:100}]}
	global const Image finger = {"lib/core/play/media/finger0.png", atlas, {57,80}, [{x1:550,y1:482,x2:603,y2:558,w:53,h:76},{x1:607,y1:482,x2:660,y2:558,w:53,h:76}]}
	global const Image Next = {"lib/core/play/media/Next.png", atlas, {68,68}, [{x1:664,y1:482,x2:728,y2:546,w:64,h:64}]}
	global const Image ThumbsUp = {"lib/core/play/media/ThumbsUp.png", atlas, {68,68}, [{x1:732,y1:482,x2:796,y2:546,w:64,h:64}]}
	global const Image Spark = {"lib/core/play/media/Spark0.png", atlas, {62,62}, [{x1:751,y1:197,x2:809,y2:255,w:58,h:58},{x1:758,y1:586,x2:806,y2:634,w:48,h:48},{x1:790,y1:392,x2:828,y2:430,w:38,h:38}]}
	global const Image Back = {"lib/core/play/media/Back.png", atlas, {52,52}, [{x1:813,y1:197,x2:861,y2:245,w:48,h:48}]}
	global const Image cameraIcon = {"lib/core/play/media/cameraIcon.png", atlas, {52,52}, [{x1:751,y1:262,x2:799,y2:310,w:48,h:48}]}
	global const Image Checkbox = {"lib/core/play/media/Checkbox0.png", atlas, {52,52}, [{x1:803,y1:262,x2:851,y2:310,w:48,h:48},{x1:750,y1:327,x2:798,y2:375,w:48,h:48}]}
	global const Image Help = {"lib/core/play/media/Help0.png", atlas, {52,52}, [{x1:802,y1:327,x2:850,y2:375,w:48,h:48},{x1:800,y1:482,x2:848,y2:530,w:48,h:48}]}
	global const Image Menu = {"lib/core/play/media/Menu.png", atlas, {52,52}, [{x1:446,y1:586,x2:494,y2:634,w:48,h:48}]}
	global const Image microphoneIcon = {"lib/core/play/media/microphoneIcon.png", atlas, {52,52}, [{x1:498,y1:586,x2:546,y2:634,w:48,h:48}]}
	global const Image New = {"lib/core/play/media/New.png", atlas, {52,52}, [{x1:550,y1:586,x2:598,y2:634,w:48,h:48}]}
	global const Image Quit = {"lib/core/play/media/Quit.png", atlas, {52,52}, [{x1:602,y1:586,x2:650,y2:634,w:48,h:48}]}
	global const Image Save = {"lib/core/play/media/Save.png", atlas, {52,52}, [{x1:654,y1:586,x2:702,y2:634,w:48,h:48}]}
	global const Image settingsIcon = {"lib/core/play/media/settingsIcon.png", atlas, {52,52}, [{x1:706,y1:586,x2:754,y2:634,w:48,h:48}]}
	global const Image speakerIcon = {"lib/core/play/media/speakerIcon.png", atlas, {52,52}, [{x1:810,y1:586,x2:858,y2:634,w:48,h:48}]}
	global const Image starParticle = {"lib/core/play/media/starParticle2.png", atlas, {52,48}, [{x1:534,y1:638,x2:560,y2:662,w:26,h:24},{x1:855,y1:262,x2:865,y2:272,w:10,h:10},{x1:446,y1:638,x2:494,y2:682,w:48,h:44}]}
	global const Image Tutorial = {"lib/core/play/media/Tutorial.png", atlas, {52,52}, [{x1:446,y1:686,x2:494,y2:734,w:48,h:48}]}
	global const Image[] Flag = [{"lib/core/play/media/Flag-Language1-State0.png", atlas, {37,25}, [{x1:654,y1:437,x2:686,y2:458,w:32,h:21},{x1:690,y1:437,x2:722,y2:458,w:32,h:21}]},{"lib/core/play/media/Flag-Language1-State0.png", atlas, {37,25}, [{x1:832,y1:392,x2:865,y2:413,w:33,h:21},{x1:617,y1:437,x2:650,y2:458,w:33,h:21}]}]
	global const Image ResizeHandle = {"lib/core/play/media/ResizeHandle.png", atlas, {36,36}, [{x1:498,y1:638,x2:530,y2:670,w:32,h:32}]}

class Sound
	global const Sound LobbyImpact = {"LobbyImpact.mp3", 1933}

class Font
	global const Font ByTheWay = {"ByTheWay", "ByTheWay.woff2"}
	global const Font OpenSans = {"OpenSans", "OpenSans.woff2"}
	global const Font ShadowedSerif = {"ShadowedSerif", "ShadowedSerif.woff2"}

transient unit Platform
	js void openMedia: void() callback
		Promise.all([$Image.atlas.open(),Font.ByTheWay.open(),Font.OpenSans.open(),Font.ShadowedSerif.open(),Sound.LobbyImpact.open()]).then(() => callback())
	cpp void openMedia
		Image::atlas->open();
		Font::ByTheWay->open();
		Font::OpenSans->open();
		Font::ShadowedSerif->open();
		Sound::LobbyImpact->open();
